version: '3'

services:
#  front:
#    image: "front-stocks:v1"
#    ports:
#      - 8080:80
  apiusers:
    image: "api-users:v1"
    ports:
      - 8082:8082
    environment:
      DB_URL: jdbc:postgresql://database:5432/stock_users
    restart: always
  apistocks:
    image: "api_stocks:v1"
    ports:
      - 8083:8083
    environment:
      DB_URL: jdbc:postgresql://database:5432/stocks
    restart: always
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: stocks
    volumes:
      - /var/usr/lib/postgresql/14/main
    restart: always