server:
    port: 8081
    error:
        include-message: always
        include-exception: true
        include-stacktrace: always
        include-binding-errors: always
config:
    api-stocks-url: ${API_STOCKS_URL:http://localhost:8083}
spring:
    profiles:
        active: ${ACTIVE_PROFILE:development}
    application:
        name: api-user-web
    flyway:
        baseline-on-migrate: true
        locations: classpath:db/migration

---
spring:
    config:
        activate:
            on-profile: development
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DB_URL:jdbc:postgresql://localhost:5432/stocks_broker_user}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWD:postgres}
        hikari:
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000
            minimum-idle: 5
            maximum-pool-size: 10
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: false
        database: postgresql
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
springdoc:
    swagger-ui:
        config-url: /v3/api-docs/swagger-config
        url: /v3/api-docs

logging:
    level:
        ROOT: info

#corrige bug no flyway
flyway:
    locations: classpath:db/migration
    outOfOrder: false
    servlet:
        multipart:
            max-file-size: 30MB
            max-request-size: 30MB

---
spring:
    config:
        activate:
            on-profile: production
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DB_URL:jdbc:postgresql://containers-us-west-207.railway.app:5770/stocks_broker_user}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWD:postgres}
        hikari:
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000
            minimum-idle: 5
            maximum-pool-size: 5
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: false
        database: postgresql
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect