#org.springframework.security.oauth2.jwt.JwtDecoder=
#spring.security.oauth2.client.registration.okta.client-id=0oa3jwkz7sKKVpxWN5d7
#spring.security.oauth2.client.registration.okta.client-secret=vdPLXZlfpq-G4ybHprHIKLOt-3iqYw8RG_SW5Ueb
#spring.security.oauth2.client.registration.okta.authorization-grant-type=client_credentials
#spring.security.oauth2.client.registration.okta.scope=mod_custom
#spring.security.oauth2.client.provider.okta.token-uri=https://dev-8471287.okta.com/oauth2/default/v1/token

server:
    port: 8082
    error:
        include-message: always
        include-exception: true
        include-stacktrace: always
        include-binding-errors: always

spring:
    profiles:
        active: ${ACTIVE_PROFILE:development}
    application:
        name: api-user-web
    flyway:
        baseline-on-migrate: true
        locations: classpath:db/migration

---
spring:
    config:
        activate:
            on-profile: development
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DB_URL:jdbc:postgresql://localhost:5432/stock_users}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWD:postgres}
        hikari:
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000
            minimum-idle: 5
            maximum-pool-size: 10
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                hbm2ddl:
                    auto: update
# Hibernate ddl auto (create, create-drop, validate, update)
springdoc:
    swagger-ui:
        config-url: /v3/api-docs/swagger-config
        url: /v3/api-docs

logging:
    level:
        ROOT: info

okta:
    oauth2:
        issuer: https://dev-8471287.okta.com/oauth2/default
        client-id: 0oa3jwkz7sKKVpxWN5d7
        client-secret: vdPLXZlfpq-G4ybHprHIKLOt-3iqYw8RG_SW5Ueb

#corrige bug no flyway
flyway:
    locations: classpath:db/migration
    outOfOrder: false
    servlet:
        multipart:
            max-file-size: 30MB
            max-request-size: 30MB
